/**
 * CKEditor 5 — NPM build entry
 * Exposes ClassicEditor on window so inline blade scripts work unchanged.
 */
import {
    ClassicEditor,
    Autoformat,
    BlockQuote,
    Bold,
    Code,
    CodeBlock,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontSize,
    Heading,
    HorizontalLine,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    LinkImage,
    List,
    MediaEmbed,
    Paragraph,
    SourceEditing,
    Strikethrough,
    Table,
    TableToolbar,
    Alignment,
    TodoList,
    Underline,
} from 'ckeditor5';

import 'ckeditor5/ckeditor5.css';

// Make ClassicEditor available globally so inline blade <script> blocks work.
window.ClassicEditor = ClassicEditor;
window.CKEditorPlugins = {
    Autoformat,
    BlockQuote,
    Bold,
    Code,
    CodeBlock,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontSize,
    Heading,
    HorizontalLine,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    LinkImage,
    List,
    MediaEmbed,
    Paragraph,
    SourceEditing,
    Strikethrough,
    Table,
    TableToolbar,
    Alignment,
    TodoList,
    Underline,
};
